### PR TITLE
added "drinks" to "food"

### PR DESCRIPTION
**Pull request by purzlbaum**
because br-bier.ch is not food ;)

### CODE REVIEW

**Comment by markhowellsmead** [comment]
Please base amendments on the newest version of the file. This PR creates a merge conflict.

**Comment by grappler** [comment]
The PR does not need to closed if the person is able rebase the PR.

**Comment by markhowellsmead** [comment]
Please rebase and resubmit.

**Comment by markhowellsmead** [comment]
Natur Konkret is missing in your version.

**Pull request closed without merging**
