### PR TITLE
Added BlueGlass ¦ Team Farner as WordPress Agency

### PR DESCRIPTION
**Pull request by GemmaNicolas**
Added BlueGlass ¦ Team Farner to wordpress-developers-and-agencies-switzerland.md

### CODE REVIEW

**Comment by markhowellsmead** [comment]
Can you provide a link to the page/s on the website (here as a comment, not in the pull request) which make a direct reference to your WordPress services or projects, please?

**Comment by GemmaNicolas** [comment]
hi @markhowellsmead 

Here the link to our **BlueGlass Website Services**: https://www.blueglass.ch/websites-applikationen

At BlueGlass, we specialize in various CMS, with a particular emphasis on WordPress with Gutenberg. Additionally, we're proud to offer a [free and open-source plugin](https://www.blueglass.ch/agentur/tools/jobs-for-wordpress-plugin).

**Comment by markhowellsmead** [comment]
Thanks for your contribution. I've removed the @ link, as this is for links to accounts on X, not LinkedIn.

**Comment by GemmaNicolas** [comment]
Ok! I thought Linkedin would have more sense being business-related. 
We do really have an account on X too : https://twitter.com/BlueGlassZRH

Thank you!

**Comment by markhowellsmead** [comment]
Thanks for your feedback. The information in this repository is intended as a reference for the WordPress community, which is primarily within social media channels. We're going to be migrating this information to our website at wpswitzerland.ch soon, and we'll discuss the viability of having the possibility to link to other channels like LinkedIn.

**Pull request merged**
