### PR TITLE
Meesterpaul patch 1

### PR DESCRIPTION
**Pull request by MeesterPaul**
Hi there, just adding to the agency and sites lists. I've also alphabetised the sites list.

### CODE REVIEW

**Comment by markhowellsmead** [comment]
Is that a WordPress agency?

**Comment by MeesterPaul** [comment]
Yes. We almost exclusively work in WordPress, although it's not so obvious from the website at the minute.

**Comment by markhowellsmead** [comment]
OK, thanks! Would be good for the community if you mentioned it ;)

**Comment by MeesterPaul** [comment]
It's on the (sadly ever growing) todo list...

**Pull request merged**
